## **ndarray (n-dimensional array)**
It is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 

### **Array Creation and Data Types**

#### From a Python List:

In [2]:
import numpy as np 

my_array = np.array([1,2,3,4,5])
my_array

array([1, 2, 3, 4, 5])

In [35]:
print(type(my_array))
my_array.shape


<class 'numpy.ndarray'>


(5,)

#### Using built_in functions:

In [8]:
#using zeroes
zeros = np.zeros((2,2))
zeros

array([[0., 0.],
       [0., 0.]])

In [10]:
#array pf ones
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
#array of random nums
random_nums = np.random.random((3,3))
random_nums

array([[0.62835583, 0.09294293, 0.5617341 ],
       [0.46690263, 0.24067803, 0.45398405],
       [0.8405684 , 0.52728024, 0.04044025]])

In [14]:
# Array with a range of values
range_array = np.arange(10)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Specifying DataTypes

In [19]:
dt = np.array([1.1,2.2,3.3,4.4,5.5],dtype=int)
dt

array([1, 2, 3, 4, 5])

#### Broadcasting:
Broadcasting allows NumPy to perform element-wise operations on arrays of different shapes.

In [30]:
array1 = np.array([1, 2, 3])
array2 = np.array([4])
result = array1 + array2
result


array([5, 6, 7])

#### Shape Manupulation

In [44]:
arr = np.array([[1,2,3,4],[5,6,7,8]])       #2-D array
print(arr.shape)

arr = arr.reshape(4,2)
print(arr.shape)
arr

(2, 4)
(4, 2)


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#### Indexing

In [3]:
# 1-D array
array_1d = np.array([10, 20, 30, 40, 50])

print("Element at index 0:", array_1d[0])  
print("Element at index 2:", array_1d[2])  
print("Element at index -1 (last element):", array_1d[-1])

Element at index 0: 10
Element at index 2: 30
Element at index -1 (last element): 50


In [4]:
# 2-D array
array_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print("Element at [0, 0] (first row, first column):", array_2d[0, 0])  
print("Element at [1, 2] (second row, third column):", array_2d[1, 2]) 
print("Element at [2, -1] (third row, last column):", array_2d[2, -1])

Element at [0, 0] (first row, first column): 10
Element at [1, 2] (second row, third column): 60
Element at [2, -1] (third row, last column): 90


In [5]:
# 3-D array
array_3d = np.array([[[ 1,  2,  3], [ 4,  5,  6]], 
                     [[ 7,  8,  9], [10, 11, 12]], 
                     [[13, 14, 15], [16, 17, 18]]])

print("Element at [0, 1, 2] (first depth, second row, third column):", array_3d[0, 1, 2])  
print("Element at [2, 0, 1] (third depth, first row, second column):", array_3d[2, 0, 1])  
print("Element at [-1, -1, -1] (last depth, last row, last column):", array_3d[-1, -1, -1])  

Element at [0, 1, 2] (first depth, second row, third column): 6
Element at [2, 0, 1] (third depth, first row, second column): 14
Element at [-1, -1, -1] (last depth, last row, last column): 18


## Examples

In [23]:
# Job titles
job_titles = np.array(["Data Analyst", "Data Scientist",
                      "Data Engineer", "Machine Learning Engineer","AI Engineer"])

# Base salary
base_salary = np.array([30000, 50000, 60000, 55000,np.nan])

# Bonus rate
bonus_rate = np.array([[.05, .1, .08, .12,np.nan]])

In [24]:
total_salary = base_salary * (1 + bonus_rate)
total_salary

array([[31500., 55000., 64800., 61600.,    nan]])

In [28]:
np.nanmean(total_salary)

np.float64(53225.0)